# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 04cd2681a7fccd013705ba7c597798e6eeff2f2b92d257b2a711851fcd8a1dae13373fe2c54481308de600f8311a166a740b0fc2576b0b9d3720ea026b021102

test:
  secret_key_base: a88ad0a88d5a20c6d2cf8bcbcfb14840348a69703bf59f470cd08a79d15b0ab71a4fd0d3ced9b7d9e66981e1cc10d2f50daf42f52e496eadccc5143294f8c3fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
